### ISSUE TITLE
Python or Node or something else preferred for server-side stuff?

### ISSUE THREAD

**Issue by peterbe** [lmorchard/ama#1]

**Comment by lmorchard** [comment]
Node's been my go-to for the past 4 or 5 years, though Python was my favorite for 10+ years before that. 

I have trouble telling whether it's true love or just technological [Stockholm syndrome](https://en.wikipedia.org/wiki/Stockholm_syndrome), though, since Node took some investment in learning that feels good to have paid off. Then again, I could have said the same thing when I ditched Perl for Python a bazillion years ago too 😁 

Python feels "heavier" to me than Node, but I have absolutely no benchmarks or proof to back that up. But who knows, maybe I'll swap back over to Python 3 soon.
