### ISSUE TITLE
What excites you most about the future of the web?

### ISSUE THREAD

**Issue by sindresorhus** [lmorchard/ama#2]

**Comment by lmorchard** [comment]
Just yesterday, I sat in a talk by @elplatt at Penguicon 2017 entitled "[Re-decentralizing the Web](https://penguicon2017.sched.com/event/A27Y)" - that's pretty much the thing that's excited me the most since things took a centralized turn in the Web 2.0 days. The excitement kind of oscillates between states of despair & hope.

Currently, I'm on the hopeful side thanks to the recent small craze around [Mastodon](https://github.com/tootsuite/mastodon) and related projects. I'm also hoping things like [micropayments in the Brave browser](https://blog.brave.com/introducing-brave-payments/) get traction and wider adoption. Really want to see more grassroots & community web presences that are sustainable - both for the places themselves and their owners.

(also apologies to @elplatt because I kind of cornered him after the talk and kermit-flailed at him.)

![kermit flail](https://68.media.tumblr.com/027910607f16d9b3ba13abbaa494d91b/tumblr_nj8ab6EaUg1u6698to1_500.gif)
